image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      yarn
      npm i pm2 -g
      pm2 start mongod
      pm2 start "MINIO_ACCESS_KEY=hydro MINIO_SECRET_KEY=hydrohydro minio server /home/gitpod/file" --name minio
      systemctl start sonic-server
      yarn build
      yarn build:ui
      yarn debug
vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.3:1NRvj3UKNTNwmYjptmUmIw==
    - vscode-icons-team.vscode-icons@10.2.0:DrQUJPtFm0woSFiyitha8Q==
    - samuelcolvin.jinjahtml@0.12.0:lFI6zKplznEZPdWvFvRHwg==
    - tabnine.tabnine-vscode
    - gruntfuggly.todo-tree
