image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      yarn
      pm2 start mongod
      pm2 start "MINIO_ACCESS_KEY=hydro MINIO_SECRET_KEY=hydrohydro minio server /home/gitpod/file" --name minio
      pm2 start "/workspace/.cargo/bin/sonic -c /workspace/.cargo/registry/src/github.com-1ecc6299db9ec823/sonic-server-1.3.0/config.cfg" --name sonic
      systemctl start sonic-server
      yarn build
      yarn build:ui
      yarn debug
vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.3:1NRvj3UKNTNwmYjptmUmIw==
    - vscode-icons-team.vscode-icons@10.2.0:DrQUJPtFm0woSFiyitha8Q==
    - samuelcolvin.jinjahtml@0.12.0:lFI6zKplznEZPdWvFvRHwg==
    - tabnine.tabnine-vscode
    - gruntfuggly.todo-tree
