version: '3'
services:
    hydro:
        image: hydrooj/hydro:latest
        restart: always
        links:
        - mongo
        volumes: 
        - ./data/config:/config
        ports:
        - 8888:8888
    mongo:
        image: mongo:latest
        restart: always
        volumes:
        - ./data/db:/data/db
