name: CI

on:
- push
- pull_request

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LICENSE_KEY: ${{ secrets.MAXMIND_KEY }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Config
      run: |
        echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > .npmrc
        git config --global user.name undefined
        git config --global user.email i@undefined.moe
    - name: Cache
      uses: c-hive/gha-yarn-cache@v1
    - name: Install
      run: yarn
    - name: Build
      run: |
        yarn build
        yarn build:ui:production
    - name: Lint
      run: yarn lint:ci
    - name: Unit Test
      run: yarn jest --runInBand
    - name: Report Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./.coverage/lcov.info
        name: codecov
    - name: Publish
      if: ${{ github.event_name == 'push' }}
      run: node build/publish.js