name: DockerBuild
on:
  push:
    branches: 
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node_version: '13.x'
    - run: |
        yarn
        yarn build:production
    - uses: actions/upload-artifact@v1
      with:
        name: hydro
        path: .build
    - run: |
        cd ui
        yarn
        yarn build:production
        cd ..
    - uses: actions/upload-artifact@v1
      with:
        name: .uibuild
        path: .uibuild
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: hydrooj/hydro:alpine
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
